# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "my-new-blog"

# 网页的标题
title: "小萌新的编程师的小世界"
username: 科技遇见小萌新😊
# 网站副标题
description: "😘这是我的小世界，记录我的生活，学习和工作感悟"

aboutme: "我的生活，工作 😉🍕🎧"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
